### ISSUE TITLE
Not able to understand what need to be done

### ISSUE THREAD

**Issue by Htrist** [tmrlvi/kaspa-crawler#1]
I wish to appear on the node map.- Great to show the world under https://kas.fyi/ how many nodes are running. Well done community for making this. 
unfortunately I don t understand the actions in the "Read Me" to make my Windows Rust not showing up on the map. 

Can you elaborate more on the steps ? I am close to no idea where to begin... Make a youtube video is the best but also a bit more description can help.

Thanks !

**Comment by bgpntx** [comment]
As I can see you have to have running Kaspa node or connect to any other known node to get their IPs:
`./kaspa_crawler.py --network kaspa-mainnet --addr 0.0.0.0:16111 -v --token=************`
_--addr_ is the address of running Kaspa node. IP info token you can get on [https://ipinfo.io/account/token](https://ipinfo.io/account/token)
Once crawler is executed it's output should be in _data/nodes.json_ file. Then you can get a png file with a map:
`./scripts/plot_map.py -i data/nodes.json`
It's written to kaspad_nodes.png file.
Something like that 🤓

**Comment by Htrist** [comment]
Thanks this is helping but still not able to proceed. 

Yes I am running my own node on Rust. (Thanks to a youtube video showing me everything)


What should I do with this  : 

**_**For the first run, you should create a virtual env and install the dependencies._**

python -m venv venv
. ./venv/bin/activate
pip install -r requirements.txt**

A step by step would be great.

**Comment by tmrlvi** [comment]
There is no way to guarantee you'll appear in the map generated by someone else, since the nodes don't send all their known peers. You can create a map starting from your node, and then it would appear.

That said, there are things that guarantee you *won't* appear in the map:
   (1) Your p2p port is closed for outside access (this is likely if you are behind a NAT)
   (2) Your node often goes down

However, this is out of the scope of the README which is intented to tell you how to run a map at all.
If you are interested, you can try to research the way the P2P protocol works, and ofter improvement to the script that will allow more visibility to more nodes.
